name: Cache Prime Workflow

on:
  push:
    branches: [ main ]

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "Runner: $RUNNER_OS"
          uname -a
          python --version || true

      - name: Ensure cache path exists
        run: |
          echo "Ensuring ~/.cache/pip exists"
          mkdir -p ~/.cache/pip
          ls -la ~/.cache || true

      - name: prime-cache-35ae665
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-35ae665

      - name: Show cache result
        run: |
          echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
          echo "Restored keys: ${{ steps.cache.outputs.cache-hit }}" || true
